# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 🫧🫧Tech Life
subtitle: '记录每一次好奇心驱动的尝试'
description: '鸡零狗碎, 乱七八糟,碎碎念,随缘更新的 Hexo 博客，娱乐生活'
keywords:
  - Hexo
  - 技术博客
  - 开发日常
  - 碎碎念
  - 开源项目
  - 好玩应用
author: msxiaoice
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://xyzz.qzz.io
# permalink: :year/:month/:day/:title/; posts/:abbrlink/ 
permalink: posts/:year/:month/:day/:abbrlink/ 
permalink_defaults: 
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# abbrlink config
abbrlink:
  alg: crc32      # 用于计算 abbrlink 的算法。支持 crc16（默认）和 crc32
  rep: hex        # abbrlink 在 URL 中的表示方式。支持 dec（默认）和 hex
  drafts: false   # 是否为草稿生成 abbrlink（默认 false）
  force: false    # 启用强制模式：在此模式下插件会忽略缓存，即使文章已有 abbrlink 也会重新计算（默认 false）
  writeback: true # 是否将更改写回 Markdown 文件的 front-matter（默认 true）

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - robots.txt

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'empty'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: butterfly


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

aplayer:
  meting: true
  asset_inject: false

sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap.xml
  template_txt: ./sitemap.txt
  rel: false
  tags: true
  categories: true